---
version: "3.1"

services:
  caddy-saml-sso:
    container_name: caddy-saml-sso
    image: golang:1.20
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 12000:12000
    env_file:
      - .env.dev
    command: >
      ./caddy.amd64 run
  saml-app:
    container_name: saml-app
    image: golang:1.20
    volumes:
      - ./saml-app/go:/app
    working_dir: /app
    command: >
      go run ./server-app.go
