#!/bin/bash
#
docker run cloudflare/cloudflared:latest tunnel --no-autoupdate run --token eyJhIjoiMGY0YTE1MTU1NDZiMzQ2YzgxMzU5ZTkzMWY5YTA0MWIiLCJ0IjoiNDkzNTRlNDYtYzU1OC00Nzk4LWEzOGQtNzlmZTEzMjRmZDUyIiwicyI6Ik9XUXdNVGczTVRrdFpqaGxaUzAwTldReExXRmxNREF0WldObFpXWTVaakEwWlRreCJ9
